# Generated by Django 5.2.7 on 2026-06-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('file', 'Fichier'), ('image', 'Image'), ('link', 'Lien Web')], default='file', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/%Y/%m/%d/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='projects.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
