"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@^76cr!=z6%u2xpmw3vwk-mj-&r+wve$^od%r^jpwu=z1@(%ct'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'drf_spectacular',   # Swagger / OpenAPI
    
    # Local apps
    'accounts',
    'projects',
    'ai_module',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# Dev  → SQLite (aucune config requise)
# Prod → PostgreSQL via DATABASE_URL dans le .env
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url
from decouple import config

_DEBUG = config('DEBUG', default=True, cast=bool)

if _DEBUG:
    # ── Développement ─────────────────────────────────────
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # ── Production (PostgreSQL) ───────────────────────────
    # Définir DATABASE_URL dans le .env de prod, ex :
    # DATABASE_URL=postgresql://user:password@host:5432/dbname
    DATABASES = {
        'default': dj_database_url.config(
            env='DATABASE_URL',
            conn_max_age=600,          # Connexions persistantes (10 min)
            conn_health_checks=True,   # Vérifie la santé de la connexion
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'accounts.CustomUser'

# Configuration REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',  # Swagger
}

# Configuration JWT
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Configuration CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://localhost:5173",
    "https://management-tasks-ch6gzvqfx-albans-projects-a6430890.vercel.app",
]

CORS_ALLOW_CREDENTIALS = False

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'albanpombombe@gmail.com'
EMAIL_HOST_PASSWORD = 'reincxepxrjuoerw'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Durée de validité de l'OTP (en minutes)
OTP_EXPIRY_MINUTES = 5

GROQ_API_KEY = config('GROQ_API_KEY', default='')

# ─── Documentation API (Swagger / ReDoc) ─────────────────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE': 'WS Task Manager — API',
    'DESCRIPTION': (
        'API REST pour la gestion de projets, tâches et utilisateurs.\n\n'
        '## Authentification\n'
        'Cette API utilise **JWT (JSON Web Token)** avec vérification OTP en 2 étapes.\n\n'
        '### Étapes de connexion\n'
        '1. `POST /api/auth/login/` → reçoit un code OTP par email\n'
        '2. `POST /api/auth/verify-otp/` → retourne les tokens `access` et `refresh`\n'
        '3. Ajouter le header : `Authorization: Bearer <access_token>` à chaque requête\n\n'
        '## Modules\n'
        '- **Auth** : Inscription, connexion OTP, profil utilisateur\n'
        '- **Users (Admin)** : Gestion complète des utilisateurs (admin uniquement)\n'
        '- **Projects** : CRUD projets + assignation des membres via `assignation_project`\n'
        '- **Tasks** : CRUD tâches, sous-tâches, commentaires, ressources, dépendances\n'
        '- **Clients** : Gestion des clients associés aux projets\n'
        '- **Notifications** : Lecture et marquage des notifications\n'
        '- **AI** : Génération de sous-tâches, synthèse, assignation intelligente, chat\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,

    # ── Sécurité JWT ──────────────────────────────────────────────────────────
    'SECURITY': [{'jwtAuth': []}],
    'SECURITY_DEFINITIONS': {
        'jwtAuth': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': (
                'Entrez votre token JWT au format : **Bearer &lt;access_token&gt;**\n\n'
                'Obtenez un token via `POST /api/auth/verify-otp/`.'
            ),
        }
    },

    # ── Interface Swagger UI ───────────────────────────────────────────────────
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 1,
        'defaultModelExpandDepth': 2,
        'docExpansion': 'list',
        'filter': True,
    },

    # ── Tags (groupes d'endpoints) ────────────────────────────────────────────
    'TAGS': [
        {'name': 'Auth',          'description': 'Inscription, connexion OTP et gestion du profil'},
        {'name': 'Users (Admin)', 'description': 'CRUD utilisateurs — accès admin uniquement'},
        {'name': 'Projects',      'description': 'CRUD projets et assignation des membres (table assignation_project)'},
        {'name': 'Tasks',         'description': 'CRUD tâches, sous-tâches, commentaires et ressources'},
        {'name': 'Clients',       'description': 'Gestion des clients associés aux projets'},
        {'name': 'Notifications', 'description': 'Lecture et marquage des notifications utilisateur'},
        {'name': 'Search',        'description': 'Recherche globale projets + tâches'},
        {'name': 'AI',            'description': 'Fonctionnalités IA : synthèse, sous-tâches, assignation et chat'},
    ],
}
